import { profileSchema } from "@/lib/validations/profile.schema";

export function extractProfileData(parsed: ReturnType<typeof profileSchema.safeParse>) {
  if (!parsed.success) return null;
  const d = parsed.data;
  return {
    source: d.source || null,
    sourceInfo: d.sourceInfo || null,
    email: d.email || null,
    altEmail: d.altEmail || null,
    phone: d.phone,
    altPhone: d.altPhone || null,
    contactPerson: d.contactPerson || null,
    creatingFor: d.creatingFor || null,
    name: d.name,
    gender: d.gender,
    dob: d.dob ? new Date(d.dob) : null,
    maritalStatus: d.maritalStatus || null,
    height: d.height || null,
    weightKg: d.weightKg || null,
    motherTongue: d.motherTongue || null,
    bodyType: d.bodyType || null,
    complexion: d.complexion || null,
    bloodGroup: d.bloodGroup || null,
    healthStatus: d.healthStatus || null,
    nativePlace: d.nativePlace || null,
    aboutYourself: d.aboutYourself || null,
    country: d.country || null,
    state: d.state || null,
    city: d.city || null,
    citizenship: d.citizenship || null,
    countryGrewUp: d.countryGrewUp || null,
    visaStatus: d.visaStatus || null,
    religion: d.religion || null,
    caste: d.caste || null,
    subCaste: d.subCaste || null,
    gotra: d.gotra || null,
    timeOfBirth: d.timeOfBirth || null,
    placeOfBirth: d.placeOfBirth || null,
    manglik: d.manglik || null,
    highestQualification: d.highestQualification || null,
    educationField: d.educationField || null,
    institute: d.institute || null,
    workLocation: d.workLocation || null,
    workingWith: d.workingWith || null,
    profession: d.profession || null,
    businessName: d.businessName || null,
    designation: d.designation || null,
    annualIncome: d.annualIncome || null,
    diet: d.diet || null,
    drinking: d.drinking || null,
    smoking: d.smoking || null,
    fatherOccupation: d.fatherOccupation || null,
    motherOccupation: d.motherOccupation || null,
    brothers: d.brothers ?? 0,
    brothersMarried: d.brothersMarried ?? 0,
    sisters: d.sisters ?? 0,
    sistersMarried: d.sistersMarried ?? 0,
    familyType: d.familyType || null,
    affluence: d.affluence || null,
    familyValues: d.familyValues || null,
    familyBio: d.familyBio || null,
    familyAnnualIncome: d.familyAnnualIncome || null,
  };
}

export function extractPartnerPreferenceData(parsed: ReturnType<typeof profileSchema.safeParse>) {
  if (!parsed.success) return null;
  const d = parsed.data;
  return {
    minAge: d.ppMinAge ?? null,
    maxAge: d.ppMaxAge ?? null,
    minHeight: d.ppMinHeight || null,
    maxHeight: d.ppMaxHeight || null,
    maritalStatus: d.ppMaritalStatus || null,
    motherTongue: d.ppMotherTongue || null,
    religion: d.ppReligion || null,
    caste: d.ppCaste || null,
    manglikStatus: d.ppManglikStatus || null,
    hasChildrenOk: d.ppHasChildrenOk || null,
    country: d.ppCountry || null,
    state: d.ppState || null,
    city: d.ppCity || null,
    qualification: d.ppQualification || null,
    workingWith: d.ppWorkingWith || null,
    profession: d.ppProfession || null,
    annualIncome: d.ppAnnualIncome || null,
    diet: d.ppDiet || null,
    drinking: d.ppDrinking || null,
    smoking: d.ppSmoking || null,
    aboutDesiredPartner: d.ppAboutDesiredPartner || null,
  };
}
